lib/remote_retro_web/router.ex
defmodule RemoteRetroWeb.Router do
  use RemoteRetroWeb, :router
  use Honeybadger.Plug

  alias RemoteRetroWeb.{PageController, AuthController}

  @auth_controller Application.get_env(:remote_retro, :auth_controller)

  if Application.get_env(:remote_retro, :env) == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  pipeline :authentication_required do
    plug(RedirectUnauthenticated)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(SetCurrentUser)
  end

  scope "/" do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/faq", PageController, :faq)
    get("/auth/google", AuthController, :index)
    get("/auth/google/callback", @auth_controller, :callback)
    get("/logout", AuthController, :logout)
  end

  scope "/retros", RemoteRetroWeb do
    pipe_through([:browser, :authentication_required])

    resources("/", RetroController, only: [:index, :create, :show])
  end
end

lib/remote_retro_web/controllers/retro_controller.ex
defmodule RemoteRetroWeb.RetroController do
  use RemoteRetroWeb, :controller
  alias RemoteRetro.{Retro, Participation, Idea}
  alias Phoenix.Token

  def index(conn, _params) do
    user = get_session(conn, "current_user")

    render(conn, "index.html", %{
      current_user: user,
      retros: recent_retros_with_action_items_preloaded(user),
    })
  end

  def show(conn, params) do
    user = get_session(conn, "current_user")

    soft_insert_participation_record!(user, params["id"])

    render(conn, "show.html", %{
      user_token: Token.sign(conn, "user", user),
      retro_uuid: params["id"],
      include_js: true,
    })
  end

  def create(conn, _params) do
    user = get_session(conn, "current_user")

    {:ok, retro} =
      %Retro{facilitator_id: user.id}
      |> Retro.changeset()
      |> Repo.insert()

    redirect(conn, to: "/retros/" <> retro.id)
  end

  defp soft_insert_participation_record!(user, retro_id) do
    %Participation{user_id: user.id, retro_id: retro_id}
    |> Participation.changeset()
    |> Repo.insert!(on_conflict: :nothing)
  end

  defp recent_retros_with_action_items_preloaded(user) do
    action_items_with_assignee =
      from(
        ai in Idea.action_items(),
        preload: [:assignee],
        order_by: [asc: ai.inserted_at]
      )

    query =
      from(
        r in assoc(user, :retros),
        limit: 10,
        preload: [ideas: ^action_items_with_assignee],
        order_by: [desc: r.inserted_at]
      )

    Repo.all(query)
  end
end

lib/remote_retro_web/views/retro_view.ex
defmodule RemoteRetroWeb.RetroView do
  use RemoteRetroWeb, :view
  import RemoteRetroWeb.IdeaView
  import RemoteRetroWeb.LayoutView, only: [app_js: 1]
end

lib/remote_retro_web/templates/retro/index.html.eex
<%= if Enum.count(@retros) == 0 do %>
  <div class="ui centered welcome tiny longer modal">
    <div class="ui center aligned basic very padded segment no-margin-bottom">
      <h2 class="ui header">Welcome, <%= assigns[:current_user].given_name %>!</h2>
      <p>
        You're about to take part in your first RemoteRetro, traversing the following stages:
      </p>
    </div>
    <div class="ui stackable attached vertical steps">
      <div class="step">
        <i class="users icon"></i>
        <div class="content">
          <div class="title">The Lobby</div>
          <div class="description">Gather the team!</div>
        </div>
      </div>
      <div class="step">
        <i class="heart icon"></i>
        <div class="content">
          <div class="title">The Retrospective Prime Directive</div>
          <div class="description">Frame the retro as a safe, collaborative space</div>
        </div>
      </div>
      <div class="step">
        <i class="idea icon"></i>
        <div class="content">
          <div class="title">Idea Generation</div>
          <div class="description">Invite ideas from participants</div>
        </div>
      </div>
      <div class="step">
        <i class="envelope outline icon"></i>
        <div class="content">
          <div class="title">Voting</div>
          <div class="description">Vote anonymously to discuss ideas</div>
        </div>
      </div>
      <div class="step">
        <i class="comments icon"></i>
        <div class="content">
          <div class="title">Action Item Generation</div>
          <div class="description">Generate and commit to action items</div>
        </div>
      </div>
      <div class="final step">
        <i class="gift icon"></i>
        <div class="content">
          <div class="title">Retrospective Close</div>
          <div class="description">Distribute action items and depart!</div>
        </div>
      </div>
    </div>
    <%= form_for @conn, Routes.retro_path(@conn, :create), [as: :retro, class: "ui form content"], fn _f -> %>
      <button type="submit" class="ui blue right labeled fluid icon button">
        Let's Create Your First Retrospective!
        <i class="arrow right icon"></i>
      </button>
    <% end %>
  </div>

  <script src="<%= Routes.static_path(@conn, "/js/jquery.min.js") %>"></script>
  <script src="<%= Routes.static_path(@conn, "/js/semantic.min.js") %>"></script>
  <script>
    $(document).ready(function() {
      $(".longer.modal").modal({
        observeChanges: true,
        closable: false,
      }).modal("show");

      $(".final.step").on("animationstart", function(){
        $(".ui.form.content").css({ opacity: 1 });
      });
    })
  </script>
<% else %>
  <div class="ui very padded basic segment">
    <h1 class="ui dividing header">My Retros:</h1>
    <ul class="retros-list">
      <%= for retro <- @retros do %>
        <li>
          <a href="<%= Routes.retro_path @conn, :show, retro %>">
            created <%= Timex.format!(retro.inserted_at, "{relative}", :relative) %>
          </a>
          <%= if Enum.count(retro.ideas) > 0 do %>
            <div class="nested-action-items-list hidden">
              <span onclick="toggleItems(this)" class="action-items-label bold">
                <i class="ui down triangle icon"></i>Action Items
              </span>
              <ul>
                <%# ideas retrieved via association are scoped to action_items %>
                <%= for idea <- retro.ideas do %>
                  <li><%= action_item_to_string(idea) %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="ui hidden divider"></div>
    <%= form_for @conn, Routes.retro_path(@conn, :create), [as: :retro, class: "ui form"], fn _f -> %>
      <button type="submit" class="ui blue right labeled icon button">
        Create a Retrospective!
        <i class="arrow right icon"></i>
      </button>
    <% end %>

    <script>
      function toggleItems(toggleIcon) {
        var nestedActionItemsListEl = toggleIcon.closest(".nested-action-items-list");
        nestedActionItemsListEl.classList.toggle("hidden");
      }
    </script>
  </div>
<% end %>

<%# prefetch retro javascript for faster loading on retro creation :) %>
<link rel="prefetch" href="<%= Routes.static_path(@conn, "/js/dll/dll.vendor.js")%>">
<link rel="prefetch" href="<%= app_js(@conn) %>">

lib/remote_retro_web/templates/retro/show.html.eex
<div class="react-root">
  <div class="ui active large centered text loader">
    Connecting...
  </div>
</div>